// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `alpha_hex`, `color_override`, `escape_ass_text`, `estimate_width`, `format_ass_time`, `kind_code`, `kind_from_code`, `make_event`, `merge_duplicates`, `outline_color_override`, `pick_fixed_lane`, `pick_scroll_lane`, `positive_or`, `write_dialogue`, `write_header`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `Kind`, `ParsedDanmaku`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_receiver_is_total_eq`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `eq`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`

double assResolveFontSize({required double inAppFontSize}) =>
    RustLib.instance.api
        .crateApiAssConverterAssResolveFontSize(inAppFontSize: inAppFontSize);

RustAssConversionResult convertDanmakuToAss(
        {required List<RustAssDanmakuInput> items,
        required RustAssExportSettings settings}) =>
    RustLib.instance.api.crateApiAssConverterConvertDanmakuToAss(
        items: items, settings: settings);

RustAssConversionResult convertPreparedDanmakuToAss(
        {required List<RustPreparedDanmakuInput> items,
        required int playResX,
        required int playResY,
        required RustAssExportSettings settings}) =>
    RustLib.instance.api.crateApiAssConverterConvertPreparedDanmakuToAss(
        items: items,
        playResX: playResX,
        playResY: playResY,
        settings: settings);

class RustAssConversionResult {
  final String ass;
  final List<RustAssEvent> events;

  const RustAssConversionResult({
    required this.ass,
    required this.events,
  });

  @override
  int get hashCode => ass.hashCode ^ events.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RustAssConversionResult &&
          runtimeType == other.runtimeType &&
          ass == other.ass &&
          events == other.events;
}

class RustAssDanmakuInput {
  final double timeSeconds;
  final String content;

  /// Bilibili/DandanPlay mode: 1/6/7 scroll, 4 bottom, 5 top.
  final int typeCode;
  final int colorRgb;

  const RustAssDanmakuInput({
    required this.timeSeconds,
    required this.content,
    required this.typeCode,
    required this.colorRgb,
  });

  @override
  int get hashCode =>
      timeSeconds.hashCode ^
      content.hashCode ^
      typeCode.hashCode ^
      colorRgb.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RustAssDanmakuInput &&
          runtimeType == other.runtimeType &&
          timeSeconds == other.timeSeconds &&
          content == other.content &&
          typeCode == other.typeCode &&
          colorRgb == other.colorRgb;
}

class RustAssEvent {
  final String content;
  final double startSeconds;
  final double endSeconds;
  final int colorRgb;

  /// Normalized mode: 1 scroll, 4 bottom, 5 top.
  final int typeCode;

  const RustAssEvent({
    required this.content,
    required this.startSeconds,
    required this.endSeconds,
    required this.colorRgb,
    required this.typeCode,
  });

  @override
  int get hashCode =>
      content.hashCode ^
      startSeconds.hashCode ^
      endSeconds.hashCode ^
      colorRgb.hashCode ^
      typeCode.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RustAssEvent &&
          runtimeType == other.runtimeType &&
          content == other.content &&
          startSeconds == other.startSeconds &&
          endSeconds == other.endSeconds &&
          colorRgb == other.colorRgb &&
          typeCode == other.typeCode;
}

class RustAssExportSettings {
  final double fontSize;
  final double opacity;
  final double displayArea;
  final double scrollDurationSeconds;
  final double timeOffsetSeconds;
  final bool mergeDuplicates;
  final String? fontFamily;

  /// 0 = none, 1 = stroke, 2 = uniform.
  final int outlineStyle;
  final double outlineWidth;

  /// 0 = none, 1 = soft, 2 = medium, 3 = strong.
  final int shadowStyle;

  const RustAssExportSettings({
    required this.fontSize,
    required this.opacity,
    required this.displayArea,
    required this.scrollDurationSeconds,
    required this.timeOffsetSeconds,
    required this.mergeDuplicates,
    this.fontFamily,
    required this.outlineStyle,
    required this.outlineWidth,
    required this.shadowStyle,
  });

  @override
  int get hashCode =>
      fontSize.hashCode ^
      opacity.hashCode ^
      displayArea.hashCode ^
      scrollDurationSeconds.hashCode ^
      timeOffsetSeconds.hashCode ^
      mergeDuplicates.hashCode ^
      fontFamily.hashCode ^
      outlineStyle.hashCode ^
      outlineWidth.hashCode ^
      shadowStyle.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RustAssExportSettings &&
          runtimeType == other.runtimeType &&
          fontSize == other.fontSize &&
          opacity == other.opacity &&
          displayArea == other.displayArea &&
          scrollDurationSeconds == other.scrollDurationSeconds &&
          timeOffsetSeconds == other.timeOffsetSeconds &&
          mergeDuplicates == other.mergeDuplicates &&
          fontFamily == other.fontFamily &&
          outlineStyle == other.outlineStyle &&
          outlineWidth == other.outlineWidth &&
          shadowStyle == other.shadowStyle;
}

class RustPreparedDanmakuInput {
  final double timeSeconds;
  final String text;
  final int typeCode;
  final int colorRgb;
  final double yPosition;
  final double width;
  final double durationSeconds;
  final bool isScroll;
  final bool isFiltered;

  const RustPreparedDanmakuInput({
    required this.timeSeconds,
    required this.text,
    required this.typeCode,
    required this.colorRgb,
    required this.yPosition,
    required this.width,
    required this.durationSeconds,
    required this.isScroll,
    required this.isFiltered,
  });

  @override
  int get hashCode =>
      timeSeconds.hashCode ^
      text.hashCode ^
      typeCode.hashCode ^
      colorRgb.hashCode ^
      yPosition.hashCode ^
      width.hashCode ^
      durationSeconds.hashCode ^
      isScroll.hashCode ^
      isFiltered.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RustPreparedDanmakuInput &&
          runtimeType == other.runtimeType &&
          timeSeconds == other.timeSeconds &&
          text == other.text &&
          typeCode == other.typeCode &&
          colorRgb == other.colorRgb &&
          yPosition == other.yPosition &&
          width == other.width &&
          durationSeconds == other.durationSeconds &&
          isScroll == other.isScroll &&
          isFiltered == other.isFiltered;
}
