// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `clone`, `fmt`, `fmt`, `fmt`

List<RustDensityPoint> analyzeDensity(
        {required List<double> times,
        required int videoDurationSeconds,
        required int segmentCount,
        required double minSegmentDuration}) =>
    RustLib.instance.api.crateApiDanmakuAnalyticsAnalyzeDensity(
        times: times,
        videoDurationSeconds: videoDurationSeconds,
        segmentCount: segmentCount,
        minSegmentDuration: minSegmentDuration);

List<RustPeakSegment> findPeakSegments(
        {required List<RustDensityPoint> points,
        required double peakThreshold}) =>
    RustLib.instance.api.crateApiDanmakuAnalyticsFindPeakSegments(
        points: points, peakThreshold: peakThreshold);

RustDensityStats densityStats({required List<RustDensityPoint> points}) =>
    RustLib.instance.api.crateApiDanmakuAnalyticsDensityStats(points: points);

List<RustDensityPoint> smoothDensity(
        {required List<RustDensityPoint> points, required int windowSize}) =>
    RustLib.instance.api.crateApiDanmakuAnalyticsSmoothDensity(
        points: points, windowSize: windowSize);

class RustDensityPoint {
  final double timePosition;
  final int count;

  const RustDensityPoint({
    required this.timePosition,
    required this.count,
  });

  @override
  int get hashCode => timePosition.hashCode ^ count.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RustDensityPoint &&
          runtimeType == other.runtimeType &&
          timePosition == other.timePosition &&
          count == other.count;
}

class RustDensityStats {
  final int totalCount;
  final double averageCount;
  final int maxCount;
  final int minCount;
  final Float64List peakPositions;

  const RustDensityStats({
    required this.totalCount,
    required this.averageCount,
    required this.maxCount,
    required this.minCount,
    required this.peakPositions,
  });

  @override
  int get hashCode =>
      totalCount.hashCode ^
      averageCount.hashCode ^
      maxCount.hashCode ^
      minCount.hashCode ^
      peakPositions.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RustDensityStats &&
          runtimeType == other.runtimeType &&
          totalCount == other.totalCount &&
          averageCount == other.averageCount &&
          maxCount == other.maxCount &&
          minCount == other.minCount &&
          peakPositions == other.peakPositions;
}

class RustPeakSegment {
  final double startPosition;
  final double endPosition;
  final int maxCount;
  final int totalCount;

  const RustPeakSegment({
    required this.startPosition,
    required this.endPosition,
    required this.maxCount,
    required this.totalCount,
  });

  @override
  int get hashCode =>
      startPosition.hashCode ^
      endPosition.hashCode ^
      maxCount.hashCode ^
      totalCount.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RustPeakSegment &&
          runtimeType == other.runtimeType &&
          startPosition == other.startPosition &&
          endPosition == other.endPosition &&
          maxCount == other.maxCount &&
          totalCount == other.totalCount;
}
