// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `build_dfm_plus_frame`, `fxhash_str`, `lower_bound`, `upper_bound`, `with_handle`, `with_layout_store`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`

/// One-time layout preparation.
/// Computes track assignments, collision avoidance, filtering, and merge.
/// Ported from DanmakuFlameMaster's DrawTask + DanmakusRetainer pipeline.
Future<DfmPlusPreparedLayout> dfmPlusPrepareLayout(
        {required DfmPlusPrepareRequest request}) =>
    RustLib.instance.api.crateApiDfmPlusDfmPlusPrepareLayout(request: request);

Future<DfmPlusFrameLayout> dfmPlusLayoutFrame(
        {required DfmPlusFrameRequest request}) =>
    RustLib.instance.api.crateApiDfmPlusDfmPlusLayoutFrame(request: request);

Future<void> dfmPlusDropLayout({required BigInt handle}) =>
    RustLib.instance.api.crateApiDfmPlusDfmPlusDropLayout(handle: handle);

/// Get font metrics for collision detection, matching the GPU renderer's computations exactly.
/// `custom_font_bytes`: optional custom font file contents.
Future<DfmPlusFontMetrics> dfmPlusFontMetrics(
        {required double fontSize,
        required double outlineWidth,
        Uint8List? customFontBytes}) =>
    RustLib.instance.api.crateApiDfmPlusDfmPlusFontMetrics(
        fontSize: fontSize,
        outlineWidth: outlineWidth,
        customFontBytes: customFontBytes);

/// Measure the rendered width of a single text string using the same font metrics
/// as the GPU glyph atlas (glyph_hor_advance → scale_to_px → max fallback).
///
/// This ensures collision detection widths match rendering widths exactly.
/// `custom_font_bytes`: optional custom font file contents (pass None to use default embedded font).
Future<double> dfmPlusMeasureTextWidth(
        {required String text,
        required double fontSize,
        Uint8List? customFontBytes}) =>
    RustLib.instance.api.crateApiDfmPlusDfmPlusMeasureTextWidth(
        text: text, fontSize: fontSize, customFontBytes: customFontBytes);

/// Measure widths of multiple text strings in a single call (amortizes font loading).
/// Returns a Vec of widths in the same order as the input texts.
Future<Float64List> dfmPlusMeasureTextWidths(
        {required List<String> texts,
        required double fontSize,
        Uint8List? customFontBytes}) =>
    RustLib.instance.api.crateApiDfmPlusDfmPlusMeasureTextWidths(
        texts: texts, fontSize: fontSize, customFontBytes: customFontBytes);

Future<DfmPlusPreparedLayout> dfmPlusPrepareLayoutFull(
        {required List<DfmPlusRawDanmakuItem> rawItems,
        required double width,
        required double height,
        required double fontSize,
        required double displayArea,
        required double scrollDurationSeconds,
        required bool allowStacking,
        required bool mergeDanmaku,
        int? maxQuantity,
        int? maxLinesPerType,
        required double trackGapRatio,
        required double outlineWidth,
        Uint8List? customFontBytes,
        required List<String> blockWords}) =>
    RustLib.instance.api.crateApiDfmPlusDfmPlusPrepareLayoutFull(
        rawItems: rawItems,
        width: width,
        height: height,
        fontSize: fontSize,
        displayArea: displayArea,
        scrollDurationSeconds: scrollDurationSeconds,
        allowStacking: allowStacking,
        mergeDanmaku: mergeDanmaku,
        maxQuantity: maxQuantity,
        maxLinesPerType: maxLinesPerType,
        trackGapRatio: trackGapRatio,
        outlineWidth: outlineWidth,
        customFontBytes: customFontBytes,
        blockWords: blockWords);

/// Input danmaku item for layout preparation.
class DfmPlusDanmakuItem {
  final double timeSeconds;
  final String text;
  final int typeCode;
  final int colorArgb;
  final bool isMe;

  /// Pre-measured paint width from the font measurer (glyph_hor_advance).
  /// When set to a positive value, skips the Rust-side heuristic and uses this directly.
  final double paintWidth;

  /// Pre-measured paint height from the font measurer.
  final double paintHeight;

  const DfmPlusDanmakuItem({
    required this.timeSeconds,
    required this.text,
    required this.typeCode,
    required this.colorArgb,
    required this.isMe,
    required this.paintWidth,
    required this.paintHeight,
  });

  @override
  int get hashCode =>
      timeSeconds.hashCode ^
      text.hashCode ^
      typeCode.hashCode ^
      colorArgb.hashCode ^
      isMe.hashCode ^
      paintWidth.hashCode ^
      paintHeight.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DfmPlusDanmakuItem &&
          runtimeType == other.runtimeType &&
          timeSeconds == other.timeSeconds &&
          text == other.text &&
          typeCode == other.typeCode &&
          colorArgb == other.colorArgb &&
          isMe == other.isMe &&
          paintWidth == other.paintWidth &&
          paintHeight == other.paintHeight;
}

/// Font metrics matching the GPU renderer's layout parameters.
class DfmPlusFontMetrics {
  /// Line ascent matching GPU's `line_ascent()`: `max(px * 0.82, max_face_ascender)`.
  final double ascent;

  /// Line descent: max face descender (absolute value).
  final double descent;

  /// Total line height = ascent + descent.
  final double lineHeight;

  /// Effective outline width in pixels, matching the GPU outline profile.
  final double outlinePx;

  const DfmPlusFontMetrics({
    required this.ascent,
    required this.descent,
    required this.lineHeight,
    required this.outlinePx,
  });

  @override
  int get hashCode =>
      ascent.hashCode ^
      descent.hashCode ^
      lineHeight.hashCode ^
      outlinePx.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DfmPlusFontMetrics &&
          runtimeType == other.runtimeType &&
          ascent == other.ascent &&
          descent == other.descent &&
          lineHeight == other.lineHeight &&
          outlinePx == other.outlinePx;
}

/// Single frame item with computed position.
/// Only contains the item index and position data — no text/style clones.
/// The Dart side uses item_index to look up text/style from PreparedLayout.items.
class DfmPlusFrameItem {
  final int itemIndex;
  final double x;
  final double y;
  final double offstageX;

  const DfmPlusFrameItem({
    required this.itemIndex,
    required this.x,
    required this.y,
    required this.offstageX,
  });

  @override
  int get hashCode =>
      itemIndex.hashCode ^ x.hashCode ^ y.hashCode ^ offstageX.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DfmPlusFrameItem &&
          runtimeType == other.runtimeType &&
          itemIndex == other.itemIndex &&
          x == other.x &&
          y == other.y &&
          offstageX == other.offstageX;
}

/// Per-frame layout result.
class DfmPlusFrameLayout {
  final List<DfmPlusFrameItem> items;

  const DfmPlusFrameLayout({
    required this.items,
  });

  @override
  int get hashCode => items.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DfmPlusFrameLayout &&
          runtimeType == other.runtimeType &&
          items == other.items;
}

/// Per-frame layout request.
class DfmPlusFrameRequest {
  final BigInt layoutHandle;
  final double currentTimeSeconds;

  const DfmPlusFrameRequest({
    required this.layoutHandle,
    required this.currentTimeSeconds,
  });

  @override
  int get hashCode => layoutHandle.hashCode ^ currentTimeSeconds.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DfmPlusFrameRequest &&
          runtimeType == other.runtimeType &&
          layoutHandle == other.layoutHandle &&
          currentTimeSeconds == other.currentTimeSeconds;
}

/// Layout preparation request.
class DfmPlusPrepareRequest {
  final List<DfmPlusDanmakuItem> items;
  final double width;
  final double height;
  final double fontSize;
  final double displayArea;
  final double scrollDurationSeconds;
  final bool allowStacking;
  final bool mergeDanmaku;
  final int? maxQuantity;
  final int? maxLinesPerType;
  final double trackGapRatio;
  final double outlineWidth;
  final List<String> blockWords;

  const DfmPlusPrepareRequest({
    required this.items,
    required this.width,
    required this.height,
    required this.fontSize,
    required this.displayArea,
    required this.scrollDurationSeconds,
    required this.allowStacking,
    required this.mergeDanmaku,
    this.maxQuantity,
    this.maxLinesPerType,
    required this.trackGapRatio,
    required this.outlineWidth,
    required this.blockWords,
  });

  @override
  int get hashCode =>
      items.hashCode ^
      width.hashCode ^
      height.hashCode ^
      fontSize.hashCode ^
      displayArea.hashCode ^
      scrollDurationSeconds.hashCode ^
      allowStacking.hashCode ^
      mergeDanmaku.hashCode ^
      maxQuantity.hashCode ^
      maxLinesPerType.hashCode ^
      trackGapRatio.hashCode ^
      outlineWidth.hashCode ^
      blockWords.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DfmPlusPrepareRequest &&
          runtimeType == other.runtimeType &&
          items == other.items &&
          width == other.width &&
          height == other.height &&
          fontSize == other.fontSize &&
          displayArea == other.displayArea &&
          scrollDurationSeconds == other.scrollDurationSeconds &&
          allowStacking == other.allowStacking &&
          mergeDanmaku == other.mergeDanmaku &&
          maxQuantity == other.maxQuantity &&
          maxLinesPerType == other.maxLinesPerType &&
          trackGapRatio == other.trackGapRatio &&
          outlineWidth == other.outlineWidth &&
          blockWords == other.blockWords;
}

/// Single prepared item with layout information.
class DfmPlusPreparedItem {
  final double timeSeconds;
  final String text;
  final int typeCode;
  final int colorArgb;
  final bool isMe;
  final double fontSizeMultiplier;
  final String? countText;
  final int trackIndex;
  final double yPosition;
  final double width;
  final double scrollSpeed;
  final bool isFiltered;
  final double durationSeconds;
  final bool isScroll;
  final double centeredX;

  const DfmPlusPreparedItem({
    required this.timeSeconds,
    required this.text,
    required this.typeCode,
    required this.colorArgb,
    required this.isMe,
    required this.fontSizeMultiplier,
    this.countText,
    required this.trackIndex,
    required this.yPosition,
    required this.width,
    required this.scrollSpeed,
    required this.isFiltered,
    required this.durationSeconds,
    required this.isScroll,
    required this.centeredX,
  });

  @override
  int get hashCode =>
      timeSeconds.hashCode ^
      text.hashCode ^
      typeCode.hashCode ^
      colorArgb.hashCode ^
      isMe.hashCode ^
      fontSizeMultiplier.hashCode ^
      countText.hashCode ^
      trackIndex.hashCode ^
      yPosition.hashCode ^
      width.hashCode ^
      scrollSpeed.hashCode ^
      isFiltered.hashCode ^
      durationSeconds.hashCode ^
      isScroll.hashCode ^
      centeredX.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DfmPlusPreparedItem &&
          runtimeType == other.runtimeType &&
          timeSeconds == other.timeSeconds &&
          text == other.text &&
          typeCode == other.typeCode &&
          colorArgb == other.colorArgb &&
          isMe == other.isMe &&
          fontSizeMultiplier == other.fontSizeMultiplier &&
          countText == other.countText &&
          trackIndex == other.trackIndex &&
          yPosition == other.yPosition &&
          width == other.width &&
          scrollSpeed == other.scrollSpeed &&
          isFiltered == other.isFiltered &&
          durationSeconds == other.durationSeconds &&
          isScroll == other.isScroll &&
          centeredX == other.centeredX;
}

/// Prepared layout result.
class DfmPlusPreparedLayout {
  final BigInt handle;
  final double width;
  final double height;
  final double scrollDurationSeconds;
  final double staticDurationSeconds;
  final List<DfmPlusPreparedItem> items;
  final Float64List itemTimes;
  final int trackCount;

  const DfmPlusPreparedLayout({
    required this.handle,
    required this.width,
    required this.height,
    required this.scrollDurationSeconds,
    required this.staticDurationSeconds,
    required this.items,
    required this.itemTimes,
    required this.trackCount,
  });

  @override
  int get hashCode =>
      handle.hashCode ^
      width.hashCode ^
      height.hashCode ^
      scrollDurationSeconds.hashCode ^
      staticDurationSeconds.hashCode ^
      items.hashCode ^
      itemTimes.hashCode ^
      trackCount.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DfmPlusPreparedLayout &&
          runtimeType == other.runtimeType &&
          handle == other.handle &&
          width == other.width &&
          height == other.height &&
          scrollDurationSeconds == other.scrollDurationSeconds &&
          staticDurationSeconds == other.staticDurationSeconds &&
          items == other.items &&
          itemTimes == other.itemTimes &&
          trackCount == other.trackCount;
}

class DfmPlusRawDanmakuItem {
  final double timeSeconds;
  final String text;
  final int typeCode;
  final int colorArgb;
  final bool isMe;

  const DfmPlusRawDanmakuItem({
    required this.timeSeconds,
    required this.text,
    required this.typeCode,
    required this.colorArgb,
    required this.isMe,
  });

  @override
  int get hashCode =>
      timeSeconds.hashCode ^
      text.hashCode ^
      typeCode.hashCode ^
      colorArgb.hashCode ^
      isMe.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DfmPlusRawDanmakuItem &&
          runtimeType == other.runtimeType &&
          timeSeconds == other.timeSeconds &&
          text == other.text &&
          typeCode == other.typeCode &&
          colorArgb == other.colorArgb &&
          isMe == other.isMe;
}
