// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `apply_operations`, `copy_optional_i64`, `copy_optional_string`, `json_error`, `normalize_array_batches`, `normalize_episode_match_record`, `normalize_watch_history_record`, `selected_object_bytes`, `sha256_hex`, `value_as_i64`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `SyncOperation`, `SyncPatch`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`

/// Parses arbitrary JSON and emits the stable, key-sorted encoding used by
/// incremental sync v1. Keeping this in Rust avoids building a second Dart
/// object graph just for canonicalization and hashing.
Future<RustSyncBlob> syncCanonicalizeJson(
        {required List<int> input, required bool pretty}) =>
    RustLib.instance.api.crateApiIncrementalSyncSyncCanonicalizeJson(
        input: input, pretty: pretty);

Future<String> syncSha256Bytes({required List<int> input}) =>
    RustLib.instance.api.crateApiIncrementalSyncSyncSha256Bytes(input: input);

/// Parses a full backup exactly once, keeps only the requested categories and
/// emits large record collections as bounded JSON batches. This avoids
/// materializing the entire `.npb` object graph in Dart before restoration.
Future<RustBackupRestorePlan> backupPrepareRestore(
        {required List<int> input,
        required bool includePreferences,
        required bool includeMediaLibraries,
        required bool includeWatchHistory,
        required bool includeEpisodeMatches,
        required bool includeAccounts,
        required PlatformInt64 batchSize}) =>
    RustLib.instance.api.crateApiIncrementalSyncBackupPrepareRestore(
        input: input,
        includePreferences: includePreferences,
        includeMediaLibraries: includeMediaLibraries,
        includeWatchHistory: includeWatchHistory,
        includeEpisodeMatches: includeEpisodeMatches,
        includeAccounts: includeAccounts,
        batchSize: batchSize);

/// Builds an entity-level diff between two flattened sync states.
Future<Uint8List> syncDiffStates(
        {required List<int> previousJson,
        required List<int> currentJson,
        required String modifiedAt,
        required String deviceId}) =>
    RustLib.instance.api.crateApiIncrementalSyncSyncDiffStates(
        previousJson: previousJson,
        currentJson: currentJson,
        modifiedAt: modifiedAt,
        deviceId: deviceId);

Future<Uint8List> syncApplyOperations(
        {required List<int> stateJson, required List<int> operationsJson}) =>
    RustLib.instance.api.crateApiIncrementalSyncSyncApplyOperations(
        stateJson: stateJson, operationsJson: operationsJson);

/// Verifies and decodes a snapshot while keeping the large state payload as
/// UTF-8 bytes. Dart only needs to materialize that state once, after all
/// remote patches have been replayed.
Future<RustSyncDecodedSnapshot> syncDecodeSnapshotState(
        {required List<int> snapshotBytes,
        required String expectedSha256,
        required String expectedRepositoryId,
        required PlatformInt64 expectedSnapshotVersion}) =>
    RustLib.instance.api.crateApiIncrementalSyncSyncDecodeSnapshotState(
        snapshotBytes: snapshotBytes,
        expectedSha256: expectedSha256,
        expectedRepositoryId: expectedRepositoryId,
        expectedSnapshotVersion: expectedSnapshotVersion);

/// Validates and replays an ordered patch chain without sending every decoded
/// operation through the FFI boundary.
Future<RustSyncPatchChainResult> syncApplyPatchChain(
        {required List<int> stateJson,
        required List<RustSyncPatchInput> patches,
        required PlatformInt64 maximumSnapshotVersion}) =>
    RustLib.instance.api.crateApiIncrementalSyncSyncApplyPatchChain(
        stateJson: stateJson,
        patches: patches,
        maximumSnapshotVersion: maximumSnapshotVersion);

class RustBackupRestorePlan {
  final PlatformInt64 version;
  final String timestamp;
  final String appVersion;
  final Uint8List preferencesJson;
  final Uint8List mediaLibrariesJson;
  final Uint8List accountsJson;
  final List<Uint8List> watchHistoryBatches;
  final List<Uint8List> episodeMatchBatches;
  final PlatformInt64 invalidWatchHistoryCount;
  final PlatformInt64 invalidEpisodeMatchCount;

  const RustBackupRestorePlan({
    required this.version,
    required this.timestamp,
    required this.appVersion,
    required this.preferencesJson,
    required this.mediaLibrariesJson,
    required this.accountsJson,
    required this.watchHistoryBatches,
    required this.episodeMatchBatches,
    required this.invalidWatchHistoryCount,
    required this.invalidEpisodeMatchCount,
  });

  @override
  int get hashCode =>
      version.hashCode ^
      timestamp.hashCode ^
      appVersion.hashCode ^
      preferencesJson.hashCode ^
      mediaLibrariesJson.hashCode ^
      accountsJson.hashCode ^
      watchHistoryBatches.hashCode ^
      episodeMatchBatches.hashCode ^
      invalidWatchHistoryCount.hashCode ^
      invalidEpisodeMatchCount.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RustBackupRestorePlan &&
          runtimeType == other.runtimeType &&
          version == other.version &&
          timestamp == other.timestamp &&
          appVersion == other.appVersion &&
          preferencesJson == other.preferencesJson &&
          mediaLibrariesJson == other.mediaLibrariesJson &&
          accountsJson == other.accountsJson &&
          watchHistoryBatches == other.watchHistoryBatches &&
          episodeMatchBatches == other.episodeMatchBatches &&
          invalidWatchHistoryCount == other.invalidWatchHistoryCount &&
          invalidEpisodeMatchCount == other.invalidEpisodeMatchCount;
}

class RustSyncBlob {
  final Uint8List bytes;
  final String sha256;

  const RustSyncBlob({
    required this.bytes,
    required this.sha256,
  });

  @override
  int get hashCode => bytes.hashCode ^ sha256.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RustSyncBlob &&
          runtimeType == other.runtimeType &&
          bytes == other.bytes &&
          sha256 == other.sha256;
}

class RustSyncDecodedSnapshot {
  final Uint8List stateJson;
  final String sha256;

  const RustSyncDecodedSnapshot({
    required this.stateJson,
    required this.sha256,
  });

  @override
  int get hashCode => stateJson.hashCode ^ sha256.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RustSyncDecodedSnapshot &&
          runtimeType == other.runtimeType &&
          stateJson == other.stateJson &&
          sha256 == other.sha256;
}

class RustSyncPatchChainResult {
  final Uint8List stateJson;
  final List<String> appliedPatchIds;

  const RustSyncPatchChainResult({
    required this.stateJson,
    required this.appliedPatchIds,
  });

  @override
  int get hashCode => stateJson.hashCode ^ appliedPatchIds.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RustSyncPatchChainResult &&
          runtimeType == other.runtimeType &&
          stateJson == other.stateJson &&
          appliedPatchIds == other.appliedPatchIds;
}

class RustSyncPatchInput {
  final Uint8List bytes;
  final String expectedSha256;
  final String expectedId;

  const RustSyncPatchInput({
    required this.bytes,
    required this.expectedSha256,
    required this.expectedId,
  });

  @override
  int get hashCode =>
      bytes.hashCode ^ expectedSha256.hashCode ^ expectedId.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RustSyncPatchInput &&
          runtimeType == other.runtimeType &&
          bytes == other.bytes &&
          expectedSha256 == other.expectedSha256 &&
          expectedId == other.expectedId;
}
