// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `cmp_utf16`, `compare_decimal_strings`, `is_decimal`, `is_subtitle_noise_token`, `natural_ordering`, `natural_parts`, `ordering_to_i32`, `regex`, `strip_leading_group_tags`

String mediaBaseNameWithoutExtension({required String pathOrName}) => RustLib
    .instance.api
    .crateApiMediaMetadataMediaBaseNameWithoutExtension(pathOrName: pathOrName);

String mediaExtractAnimeTitleKeyword({required String pathOrName}) => RustLib
    .instance.api
    .crateApiMediaMetadataMediaExtractAnimeTitleKeyword(pathOrName: pathOrName);

int naturalCompare({required String a, required String b}) =>
    RustLib.instance.api.crateApiMediaMetadataNaturalCompare(a: a, b: b);

/// Preserves the provider's older natural-sort behavior: text is case-sensitive
/// and equal numeric values do not use their zero-padding as a tiebreaker.
int naturalCompareCaseSensitive({required String a, required String b}) =>
    RustLib.instance.api
        .crateApiMediaMetadataNaturalCompareCaseSensitive(a: a, b: b);

String subtitleNormalizeMatchName({required String name}) =>
    RustLib.instance.api
        .crateApiMediaMetadataSubtitleNormalizeMatchName(name: name);

List<String> subtitleExtractMatchTokens({required String name}) =>
    RustLib.instance.api
        .crateApiMediaMetadataSubtitleExtractMatchTokens(name: name);

String? subtitlePickLikelyEpisodeNumber({required List<String> numbers}) =>
    RustLib.instance.api
        .crateApiMediaMetadataSubtitlePickLikelyEpisodeNumber(numbers: numbers);

int subtitleComputeMatchScore(
        {required String videoName,
        required String subtitleName,
        required String extension_,
        required List<String> videoNumbers,
        String? episodeNumber}) =>
    RustLib.instance.api.crateApiMediaMetadataSubtitleComputeMatchScore(
        videoName: videoName,
        subtitleName: subtitleName,
        extension_: extension_,
        videoNumbers: videoNumbers,
        episodeNumber: episodeNumber);
