// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `apply_auth`, `common_headers`, `credentials_from_url`, `extract_file_name`, `fetch_file_size_via_propfind`, `parse_content_disposition_file_name`, `parse_content_range`, `parse_positive_header`, `should_bypass_proxy`, `strip_quotes`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `fmt`

Future<RustMediaProbeResult> probeRemoteMedia(
        {required String originalUrl,
        int? maxHashLength,
        int? timeoutSeconds}) =>
    RustLib.instance.api.crateApiMediaProbeProbeRemoteMedia(
        originalUrl: originalUrl,
        maxHashLength: maxHashLength,
        timeoutSeconds: timeoutSeconds);

Future<String> hashFileHead({required String filePath, int? maxBytes}) =>
    RustLib.instance.api
        .crateApiMediaProbeHashFileHead(filePath: filePath, maxBytes: maxBytes);

class RustMediaProbeResult {
  final String fileName;
  final PlatformInt64 fileSize;
  final int bytesHashed;
  final String hash;

  const RustMediaProbeResult({
    required this.fileName,
    required this.fileSize,
    required this.bytesHashed,
    required this.hash,
  });

  @override
  int get hashCode =>
      fileName.hashCode ^
      fileSize.hashCode ^
      bytesHashed.hashCode ^
      hash.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RustMediaProbeResult &&
          runtimeType == other.runtimeType &&
          fileName == other.fileName &&
          fileSize == other.fileSize &&
          bytesHashed == other.bytesHashed &&
          hash == other.hash;
}
