// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `compare_entries`

/// Sorts a complete remote directory in one Rust task and returns the original
/// indices in display order. Keeping the payload columnar avoids creating a
/// second remote-file model across the FFI boundary.
Future<Uint32List> sortRemoteEntryIndices(
        {required List<String> names,
        required List<bool> isDirectories,
        required Int64List sizes,
        required Int64List modifiedMillis,
        required int preset}) =>
    RustLib.instance.api.crateApiRemoteDirectorySortRemoteEntryIndices(
        names: names,
        isDirectories: isDirectories,
        sizes: sizes,
        modifiedMillis: modifiedMillis,
        preset: preset);
