// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `finish_capture`, `finish`, `handle_empty`, `handle_end`, `handle_start`, `is_video_file`, `name_eq`, `new`, `push_text`, `start_capture`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `ResponseState`, `TextCapture`, `TextField`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`

/// Parses one complete WebDAV PROPFIND multistatus response off the Dart UI
/// isolate. Namespace prefixes are ignored and only the first propstat/prop,
/// matching the legacy Dart parser, contributes metadata.
Future<List<RustWebDavEntry>> parseWebdavMultistatus(
        {required String xml,
        required String basePath,
        required bool includeAllFiles}) =>
    RustLib.instance.api.crateApiWebdavMultistatusParseWebdavMultistatus(
        xml: xml, basePath: basePath, includeAllFiles: includeAllFiles);

class RustWebDavEntry {
  final String name;
  final String path;
  final bool isDirectory;
  final PlatformInt64? size;
  final String? lastModified;

  const RustWebDavEntry({
    required this.name,
    required this.path,
    required this.isDirectory,
    this.size,
    this.lastModified,
  });

  @override
  int get hashCode =>
      name.hashCode ^
      path.hashCode ^
      isDirectory.hashCode ^
      size.hashCode ^
      lastModified.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RustWebDavEntry &&
          runtimeType == other.runtimeType &&
          name == other.name &&
          path == other.path &&
          isDirectory == other.isDirectory &&
          size == other.size &&
          lastModified == other.lastModified;
}
