name: Analyze

on:
  workflow_dispatch:
  push:
    branches: [main]

permissions:
  contents: read

concurrency:
  group: analyze-${{ github.ref_name }}
  cancel-in-progress: true

jobs:
  analyze:
    name: Flutter Analyze
    runs-on: ubuntu-latest
    env:
      ERIKA_PREBUILT: "1"
      ERIKA_PREBUILT_TAG: v0.1.6
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ github.token }}
          fetch-depth: 0
          submodules: recursive

      - name: Setup Flutter Environment
        uses: ./.github/actions/setup-flutter

      - name: Flutter Analyze
        run: flutter analyze --no-fatal-infos --no-fatal-warnings lib
